// ============================================================
// FinQuest — Module Content Data
// All 5 modules with lessons & quiz banks
// ============================================================

import type { GameModule } from "./types";

export const GAME_MODULES: GameModule[] = [
    // ================================================================
    // MODULE 1: BUDGETING & SAVING
    // ================================================================
    {
        slug: "budgeting",
        title: "Budgeting & Saving",
        subtitle: "City Builder",
        description: "Learn to allocate your resources wisely — like building a thriving city from scratch.",
        icon: "Wallet",
        color: "#6c5ce7",
        gradientFrom: "#6c5ce7",
        gradientTo: "#a29bfe",
        difficulty: "beginner",
        estimatedMinutes: 15,
        lessons: [
            {
                id: "b1",
                title: "Why Budgeting Matters",
                content: "A budget is your financial blueprint. Without one, money slips through the cracks like water through a sieve. Studies show that people who budget save 2-3x more than those who don't.\n\nThink of your income as the total resources for building a city. Every rupee needs a job — housing, food, transport, entertainment, or savings. When you assign each rupee a purpose, you take control of your financial destiny.",
                keyTakeaway: "A budget doesn't restrict you — it gives you permission to spend guilt-free on what matters.",
                icon: "Lightbulb",
            },
            {
                id: "b2",
                title: "The 50/30/20 Rule",
                content: "The most powerful budgeting framework is elegantly simple:\n\n• 50% Needs — Rent, groceries, utilities, insurance, minimum debt payments\n• 30% Wants — Dining out, entertainment, shopping, subscriptions\n• 20% Savings — Emergency fund, investments, extra debt payments\n\nExample: On a ₹50,000 salary:\n• ₹25,000 for needs\n• ₹15,000 for wants\n• ₹10,000 for savings & investments",
                keyTakeaway: "Start with 50/30/20, then adjust based on your goals. Even a rough budget beats no budget.",
                icon: "PieChart",
                interactiveExample: {
                    type: "calculator",
                    label: "Try the Budget Calculator",
                    description: "Head to the Playground to allocate your own budget",
                },
            },
            {
                id: "b3",
                title: "Emergency Fund: Your Financial Shield",
                content: "An emergency fund is money set aside for unexpected expenses — medical bills, car repairs, job loss. Financial experts recommend:\n\n• Starter goal: ₹10,000-₹25,000 (for immediate emergencies)\n• Solid goal: 3 months of expenses\n• Fortress goal: 6 months of expenses\n\nWhere to keep it: A high-yield savings account or liquid fund — accessible within 24 hours, but not so accessible that you're tempted to spend it.",
                keyTakeaway: "An emergency fund turns a crisis into an inconvenience. Start with ₹500/month if that's all you can manage.",
                icon: "Shield",
            },
            {
                id: "b4",
                title: "Tracking & Automating",
                content: "The best budget is one you actually follow. Two strategies that work:\n\n1. Expense Tracking: Record every spend for 30 days. You'll be shocked where money goes. Apps, spreadsheets, or even a notebook work.\n\n2. Automation: Set up auto-transfers on payday:\n   • Auto-transfer 20% to savings account\n   • Auto-pay all bills\n   • What remains is your spending money\n\nThis removes willpower from the equation. You can't spend what you've already saved.",
                keyTakeaway: "Automate your savings on payday. What you don't see, you don't spend.",
                icon: "RefreshCw",
            },
        ],
        quiz: [
            {
                id: "bq1",
                type: "mcq",
                question: "In the 50/30/20 rule, what percentage goes to savings and investments?",
                options: ["10%", "20%", "30%", "50%"],
                correctIndex: 1,
                explanation: "The 50/30/20 rule allocates 50% to needs, 30% to wants, and 20% to savings & investments.",
                xpReward: 20,
            },
            {
                id: "bq2",
                type: "true-false",
                question: "An emergency fund should ideally cover 3-6 months of living expenses.",
                correctAnswer: true,
                explanation: "Financial experts recommend having 3-6 months of expenses saved as an emergency fund for financial security.",
                xpReward: 20,
            },
            {
                id: "bq3",
                type: "mcq",
                question: "Which of these is classified as a 'need' in the 50/30/20 framework?",
                options: ["Netflix subscription", "Gym membership", "Rent payment", "Weekend dining"],
                correctIndex: 2,
                explanation: "Rent is a basic necessity. Netflix, gym, and dining out are 'wants' — nice to have but not essential for survival.",
                xpReward: 20,
            },
            {
                id: "bq4",
                type: "scenario",
                question: "You just got your salary of ₹60,000. What's the smartest first move?",
                scenario: "It's payday! Your account shows ₹60,000. You have bills due, a friend's birthday dinner this weekend, and you've been eyeing a new gadget.",
                options: [
                    { label: "Pay all bills first, then decide", description: "Bills come first, figure out the rest later" },
                    { label: "Auto-transfer savings, then pay bills", description: "Save first, then handle obligations" },
                    { label: "Buy the gadget before it sells out", description: "Opportunities don't wait" },
                    { label: "Split equally between everything", description: "Equal allocation across all needs" },
                ],
                correctIndex: 1,
                explanation: "Pay yourself first! Auto-transferring savings on payday ensures you save consistently. Then pay bills, and what remains is guilt-free spending money.",
                xpReward: 25,
            },
            {
                id: "bq5",
                type: "mcq",
                question: "Where should you keep your emergency fund?",
                options: ["Under your mattress", "In stocks for growth", "High-yield savings or liquid fund", "Fixed deposit for 5 years"],
                correctIndex: 2,
                explanation: "Emergency funds need to be liquid (accessible in 24-48 hours) and safe. A high-yield savings account or liquid mutual fund is ideal.",
                xpReward: 20,
            },
            {
                id: "bq6",
                type: "true-false",
                question: "Tracking expenses for 30 days can reveal spending patterns you weren't aware of.",
                correctAnswer: true,
                explanation: "Most people are surprised by their spending patterns. Tracking reveals 'money leaks' — small, recurring expenses that add up significantly.",
                xpReward: 20,
            },
            {
                id: "bq7",
                type: "slider",
                question: "If you earn ₹40,000/month and follow the 50/30/20 rule, how much goes to savings?",
                min: 0,
                max: 20000,
                step: 1000,
                unit: "₹",
                correctValue: 8000,
                tolerance: 5,
                explanation: "20% of ₹40,000 = ₹8,000. This goes toward emergency fund, investments, and extra debt payments.",
                xpReward: 25,
            },
            {
                id: "bq8",
                type: "mcq",
                question: "What's the biggest benefit of automating your savings?",
                options: [
                    "You earn more interest",
                    "It removes the need for willpower",
                    "Banks give you rewards",
                    "It's required by law",
                ],
                correctIndex: 1,
                explanation: "Automation removes the temptation to spend first. When savings are transferred automatically, you adapt your lifestyle to what remains.",
                xpReward: 20,
            },
        ],
    },

    // ================================================================
    // MODULE 2: COMPOUND INTEREST
    // ================================================================
    {
        slug: "compound-interest",
        title: "Compound Interest",
        subtitle: "Time Machine",
        description: "Discover how time turns small amounts into fortunes. Watch your money grow through decades.",
        icon: "TrendingUp",
        color: "#00cec9",
        gradientFrom: "#00cec9",
        gradientTo: "#81ecec",
        difficulty: "beginner",
        estimatedMinutes: 15,
        lessons: [
            {
                id: "ci1",
                title: "The 8th Wonder of the World",
                content: "Einstein (supposedly) called compound interest the 8th wonder of the world. Here's why:\n\nSimple interest: You earn interest only on your original amount.\nCompound interest: You earn interest on your original amount AND on the interest already earned.\n\nExample: ₹1,00,000 at 10% per year\n• Simple interest after 20 years: ₹3,00,000\n• Compound interest after 20 years: ₹6,72,750\n\nThat's 2.24x more — just from interest earning interest!",
                keyTakeaway: "Compound interest makes your money work for you, and then makes that money work for you too.",
                icon: "Sparkles",
            },
            {
                id: "ci2",
                title: "The Rule of 72",
                content: "Want a quick way to know how long it takes to double your money? Divide 72 by the interest rate.\n\n• At 6% → 72/6 = 12 years to double\n• At 8% → 72/8 = 9 years to double\n• At 12% → 72/12 = 6 years to double\n• At 15% → 72/15 = 4.8 years to double\n\nThis means at 12% return, ₹1 lakh becomes ₹2 lakh in 6 years, ₹4 lakh in 12 years, ₹8 lakh in 18 years, and ₹16 lakh in 24 years!",
                keyTakeaway: "Rule of 72: Divide 72 by your interest rate to estimate doubling time. Higher returns = faster doubling.",
                icon: "Calculator",
                interactiveExample: {
                    type: "calculator",
                    label: "Try the Compound Interest Calculator",
                    description: "Head to the Playground to see your money grow",
                },
            },
            {
                id: "ci3",
                title: "Time: Your Greatest Ally",
                content: "The most powerful variable in compound interest is TIME, not money.\n\nConsider two friends:\n• Priya invests ₹5,000/month from age 25 to 35 (10 years, total invested: ₹6 lakh)\n• Rahul invests ₹5,000/month from age 35 to 60 (25 years, total invested: ₹15 lakh)\n\nAt 12% annual return:\n• Priya at 60: ₹2.35 Crore (invested only ₹6 lakh!)\n• Rahul at 60: ₹95 lakh (invested ₹15 lakh)\n\nPriya invested less money for less time but ended up with 2.5x more. That's the power of starting early.",
                keyTakeaway: "Start investing NOW. Even small amounts grow massive over time. The best time was yesterday; the second best time is today.",
                icon: "Clock",
            },
            {
                id: "ci4",
                title: "APR vs APY: What You Actually Earn",
                content: "Two important terms:\n\n• APR (Annual Percentage Rate): The stated interest rate without compounding\n• APY (Annual Percentage Yield): The actual rate you earn when compounding is included\n\nCompounding frequency matters:\n₹1,00,000 at 12% APR for 1 year:\n• Annual compounding: ₹1,12,000 (APY = 12%)\n• Monthly compounding: ₹1,12,683 (APY = 12.68%)\n• Daily compounding: ₹1,12,747 (APY = 12.75%)\n\nMore frequent compounding = higher effective return.",
                keyTakeaway: "Always look at APY, not APR. More frequent compounding means more money in your pocket.",
                icon: "Percent",
            },
        ],
        quiz: [
            {
                id: "ciq1",
                type: "mcq",
                question: "What makes compound interest more powerful than simple interest?",
                options: [
                    "The bank gives a higher rate",
                    "You earn interest on interest",
                    "The government adds extra money",
                    "You can withdraw more often",
                ],
                correctIndex: 1,
                explanation: "Compound interest earns interest on your principal AND on previously earned interest, creating exponential growth over time.",
                xpReward: 20,
            },
            {
                id: "ciq2",
                type: "slider",
                question: "Using the Rule of 72, how many years to double your money at 8% return?",
                min: 1,
                max: 20,
                step: 1,
                unit: "years",
                correctValue: 9,
                tolerance: 10,
                explanation: "Rule of 72: 72 ÷ 8 = 9 years. At 8% annual return, your money doubles approximately every 9 years.",
                xpReward: 25,
            },
            {
                id: "ciq3",
                type: "scenario",
                question: "Who ends up with more money at age 60?",
                scenario: "Anita starts investing ₹3,000/month at age 22 and stops at 32. Vijay starts investing ₹5,000/month at age 32 and continues until 60. Both earn 12% annual return.",
                options: [
                    { label: "Anita", description: "Started early but invested for only 10 years" },
                    { label: "Vijay", description: "Started later but invested for 28 years with more money" },
                    { label: "They end up equal", description: "Early start offsets larger contributions" },
                    { label: "Impossible to tell", description: "Need more information" },
                ],
                correctIndex: 0,
                explanation: "Anita: invested ₹3.6L total, grows to ~₹2.1 Cr. Vijay: invested ₹16.8L total, grows to ~₹1.8 Cr. Starting early with less beats starting late with more.",
                xpReward: 25,
            },
            {
                id: "ciq4",
                type: "true-false",
                question: "APY (Annual Percentage Yield) includes the effect of compounding, while APR does not.",
                correctAnswer: true,
                explanation: "APR is the stated rate; APY is the effective rate including compounding. APY is always ≥ APR.",
                xpReward: 20,
            },
            {
                id: "ciq5",
                type: "mcq",
                question: "Which compounding frequency gives the highest return?",
                options: ["Annual", "Quarterly", "Monthly", "Daily"],
                correctIndex: 3,
                explanation: "More frequent compounding means you earn interest on interest more often. Daily > Monthly > Quarterly > Annual.",
                xpReward: 20,
            },
            {
                id: "ciq6",
                type: "mcq",
                question: "What's the most powerful variable in compound interest?",
                options: ["Interest rate", "Principal amount", "Time", "Compounding frequency"],
                correctIndex: 2,
                explanation: "While all variables matter, time has the greatest impact due to the exponential nature of compounding. This is why starting early is crucial.",
                xpReward: 20,
            },
            {
                id: "ciq7",
                type: "slider",
                question: "At 12% annual return, ₹1 lakh roughly becomes how much in 24 years?",
                min: 200000,
                max: 2500000,
                step: 100000,
                unit: "₹",
                correctValue: 1600000,
                tolerance: 15,
                explanation: "At 12%, money doubles every 6 years (72÷12). In 24 years, it doubles 4 times: ₹1L → ₹2L → ₹4L → ₹8L → ₹16L.",
                xpReward: 25,
            },
            {
                id: "ciq8",
                type: "true-false",
                question: "If you start investing 10 years later, you can compensate by simply investing twice the amount.",
                correctAnswer: false,
                explanation: "Due to exponential growth, a 10-year head start is nearly impossible to overcome by just doubling contributions. Priya vs Rahul example proves this.",
                xpReward: 20,
            },
        ],
    },

    // ================================================================
    // MODULE 3: INSURANCE
    // ================================================================
    {
        slug: "insurance",
        title: "Insurance",
        subtitle: "Shield Forge",
        description: "Craft protection against life's unexpected events. Shield your wealth and your family.",
        icon: "Shield",
        color: "#fd79a8",
        gradientFrom: "#fd79a8",
        gradientTo: "#fab1ce",
        difficulty: "intermediate",
        estimatedMinutes: 15,
        lessons: [
            {
                id: "i1",
                title: "Insurance: Not 'If' But 'When'",
                content: "Insurance is a risk transfer mechanism. You pay a small, known amount (premium) to avoid a potentially devastating unknown cost.\n\nThink of it like this:\n• Without insurance: You gamble with your entire savings\n• With insurance: You pay a small fee and the insurer takes the risk\n\nKey types you need:\n1. Health Insurance — medical expenses\n2. Term Life Insurance — income replacement for dependents\n3. Motor Insurance — vehicle damage & third-party liability\n4. Home Insurance — property protection",
                keyTakeaway: "Insurance isn't an expense — it's a risk management strategy that protects your wealth from catastrophic events.",
                icon: "Shield",
            },
            {
                id: "i2",
                title: "Health Insurance Essentials",
                content: "A single hospitalization can wipe out years of savings. Health insurance is non-negotiable.\n\nKey concepts:\n• Sum Insured: Maximum amount the insurer will pay\n• Premium: Annual amount you pay\n• Co-pay: Your share of each claim (e.g., 10%)\n• Waiting Period: Time before certain conditions are covered\n• Network Hospitals: Cashless treatment facilities\n\nHow much coverage? Rule of thumb: At least 10x your monthly income, or ₹10 lakh minimum. Consider a top-up plan for additional coverage at lower cost.",
                keyTakeaway: "Get health insurance early — premiums are lower, and you avoid pre-existing condition waiting periods.",
                icon: "Heart",
            },
            {
                id: "i3",
                title: "Term Life Insurance: Pure Protection",
                content: "Term insurance is the purest form of life insurance:\n• High coverage at very low cost\n• No investment component (unlike LIC endowment plans)\n• Pays out only if you die during the term\n\nWho needs it? Anyone with dependents (spouse, children, parents).\n\nHow much? 10-15x your annual income.\nFor how long? Until your youngest child is financially independent or until retirement.\n\nA 30-year old can get ₹1 Crore coverage for just ₹700-900/month.\n\nAvoid: ULIPs, endowment plans, money-back policies — they mix insurance and investment poorly.",
                keyTakeaway: "Buy term insurance, invest the rest. A ₹1 Cr term plan costs less than your Netflix subscription.",
                icon: "Users",
            },
            {
                id: "i4",
                title: "Premium vs Coverage: Finding the Balance",
                content: "The goal is maximum protection at minimum cost. Key strategies:\n\n1. Buy early: A 25-year-old pays 40% less premium than a 35-year-old for the same coverage\n2. Don't over-insure: Match coverage to actual needs\n3. Increase deductibles: Higher deductible = lower premium (if you can afford the deductible)\n4. Compare plans: Use comparison websites, don't just go with your bank's offer\n5. Top-up plans: Add ₹25-50 lakh coverage at fraction of base policy cost\n\nThe premium should be a small, comfortable amount relative to your income — typically 3-5% of annual income across all insurance.",
                keyTakeaway: "Buy the right amount of coverage — not too little (under-protected) or too much (over-paying premiums).",
                icon: "Scale",
            },
        ],
        quiz: [
            {
                id: "iq1",
                type: "mcq",
                question: "What is insurance fundamentally?",
                options: [
                    "An investment that grows over time",
                    "A risk transfer mechanism",
                    "A government savings scheme",
                    "A tax-saving tool only",
                ],
                correctIndex: 1,
                explanation: "Insurance transfers financial risk from you to the insurer. You pay a small premium to avoid potentially catastrophic costs.",
                xpReward: 20,
            },
            {
                id: "iq2",
                type: "true-false",
                question: "Term life insurance has no investment component — it only pays out if you die during the term.",
                correctAnswer: true,
                explanation: "Term insurance is pure protection. Unlike endowment or ULIP plans, it doesn't mix insurance with investment, which makes it very affordable.",
                xpReward: 20,
            },
            {
                id: "iq3",
                type: "mcq",
                question: "How much health insurance coverage should you ideally have?",
                options: [
                    "₹1 lakh is enough",
                    "Whatever the cheapest plan offers",
                    "At least 10x monthly income or ₹10 lakh minimum",
                    "Your employer's group insurance is sufficient",
                ],
                correctIndex: 2,
                explanation: "Medical inflation is ~15% per year. A single surgery can cost ₹5-15 lakh. Coverage of at least ₹10 lakh (or 10x monthly income) is recommended.",
                xpReward: 20,
            },
            {
                id: "iq4",
                type: "scenario",
                question: "Rahul is 28, single, no dependents, earns ₹8 LPA. What insurance should he prioritize?",
                scenario: "Rahul just started his career 3 years ago. He's healthy, single, rents an apartment, and has no loans.",
                options: [
                    { label: "₹1 Cr term life insurance", description: "Protect his future family" },
                    { label: "Health insurance + basic term plan", description: "Health is immediate priority, term can start now cheaply" },
                    { label: "ULIP for insurance + investment", description: "Two birds with one stone" },
                    { label: "No insurance needed yet", description: "He's young and healthy" },
                ],
                correctIndex: 1,
                explanation: "Health insurance is urgent — one hospitalization can drain savings. A basic term plan is smart to lock in low premiums. ULIPs are expensive and combine insurance and investment poorly.",
                xpReward: 25,
            },
            {
                id: "iq5",
                type: "mcq",
                question: "What is a 'waiting period' in health insurance?",
                options: [
                    "Time before the policy becomes active after a claim",
                    "Time before pre-existing conditions are covered",
                    "Time you must wait in the hospital",
                    "The period between premium payments",
                ],
                correctIndex: 1,
                explanation: "Most health policies have a 2-4 year waiting period for pre-existing conditions. This is why buying insurance early (before health issues arise) is ideal.",
                xpReward: 20,
            },
            {
                id: "iq6",
                type: "slider",
                question: "If you earn ₹12 LPA, what's the recommended term life coverage?",
                min: 2000000,
                max: 25000000,
                step: 1000000,
                unit: "₹",
                correctValue: 15000000,
                tolerance: 20,
                explanation: "Rule of thumb: 10-15x annual income. At ₹12 LPA, that's ₹1.2 Cr to ₹1.8 Cr. ₹1.5 Cr is a solid middle ground.",
                xpReward: 25,
            },
            {
                id: "iq7",
                type: "true-false",
                question: "A higher deductible on your health insurance means a lower premium.",
                correctAnswer: true,
                explanation: "A deductible is the amount you pay before insurance kicks in. Higher deductible = lower premium. Choose based on what you can comfortably pay out-of-pocket.",
                xpReward: 20,
            },
            {
                id: "iq8",
                type: "mcq",
                question: "Why is buying insurance early better?",
                options: [
                    "Insurance companies give discounts for loyalty",
                    "Lower premiums and no pre-existing condition issues",
                    "Early policies have higher returns",
                    "The government mandates it",
                ],
                correctIndex: 1,
                explanation: "Younger = healthier = lower premiums. Plus, you avoid pre-existing condition waiting periods and exclusions.",
                xpReward: 20,
            },
        ],
    },

    // ================================================================
    // MODULE 4: MUTUAL FUNDS & INVESTING
    // ================================================================
    {
        slug: "mutual-funds",
        title: "Mutual Funds & Investing",
        subtitle: "Portfolio Quest",
        description: "Build your investment party. Learn diversification, SIPs, and how to grow wealth over time.",
        icon: "BarChart3",
        color: "#fdcb6e",
        gradientFrom: "#fdcb6e",
        gradientTo: "#ffeaa7",
        difficulty: "intermediate",
        estimatedMinutes: 20,
        lessons: [
            {
                id: "mf1",
                title: "What Are Mutual Funds?",
                content: "A mutual fund pools money from thousands of investors and invests it in stocks, bonds, or other assets. A professional fund manager makes the investment decisions.\n\nWhy mutual funds?\n• Diversification: Don't put all eggs in one basket\n• Professional management: Experts pick investments for you\n• Affordable: Start with as little as ₹100/month via SIP\n• Regulated: SEBI oversees all mutual funds in India\n\nKey term — NAV (Net Asset Value): The per-unit price of a mutual fund. If NAV is ₹50 and you invest ₹5,000, you get 100 units.",
                keyTakeaway: "Mutual funds are the easiest way for beginners to access professional money management and diversification.",
                icon: "Layers",
            },
            {
                id: "mf2",
                title: "Types of Mutual Funds",
                content: "Funds are categorized by what they invest in:\n\n1. Equity Funds — Invest in stocks. Higher risk, higher potential return.\n   • Large cap: Stable, large companies (lower risk)\n   • Mid cap: Growing companies (medium risk)\n   • Small cap: Small companies (higher risk, higher potential)\n\n2. Debt Funds — Invest in bonds/FDs. Lower risk, stable returns.\n   • Liquid funds: Ultra-short term, like a better savings account\n   • Short-term bond funds: 1-3 year horizon\n\n3. Hybrid Funds — Mix of equity + debt. Balanced approach.\n\n4. Index Funds — Track an index (Nifty 50, Sensex). Very low cost, no active management.",
                keyTakeaway: "Match the fund type to your goal: equity for long-term growth, debt for safety, index for low-cost market returns.",
                icon: "Grid3x3",
            },
            {
                id: "mf3",
                title: "SIP: The Power of Consistency",
                content: "SIP (Systematic Investment Plan) is investing a fixed amount every month automatically.\n\nWhy SIP works:\n1. Rupee Cost Averaging: You buy more units when prices are low, fewer when high. Over time, this averages out to a good price.\n2. Disciplined investing: Automatic — no need to time the market\n3. Power of compounding: Small amounts grow massive over time\n\nSIP of ₹5,000/month at 12% return:\n• After 10 years: ₹11.6 lakh (invested ₹6 lakh)\n• After 20 years: ₹49.9 lakh (invested ₹12 lakh)\n• After 30 years: ₹1.76 crore (invested ₹18 lakh)",
                keyTakeaway: "A SIP of ₹5,000/month can make you a crorepati in 30 years. Start today, not tomorrow.",
                icon: "Repeat",
            },
            {
                id: "mf4",
                title: "Risk Profiles & Diversification",
                content: "Your risk profile depends on:\n• Age: Younger = can take more risk (more time to recover)\n• Goals: Short-term goals need safer investments\n• Income stability: Stable job = can take more risk\n• Temperament: Can you sleep at night if markets drop 30%?\n\nAsset Allocation Rule of Thumb:\nEquity % = 100 minus your age\n• Age 25: 75% equity, 25% debt\n• Age 40: 60% equity, 40% debt\n• Age 55: 45% equity, 55% debt\n\nDiversification means spreading investments across different asset types, sectors, and geographies to reduce risk.",
                keyTakeaway: "Don't put all your money in one fund. Diversify across equity, debt, and different fund categories.",
                icon: "PieChart",
            },
            {
                id: "mf5",
                title: "How to Pick a Mutual Fund",
                content: "Key metrics to evaluate:\n\n1. Past Performance: Check 3, 5, and 10-year returns (but past performance ≠ future results)\n2. Expense Ratio: Annual fee charged by the fund. Lower is better.\n   • Index funds: 0.1-0.5%\n   • Active funds: 0.5-2.5%\n3. Fund Manager Track Record: How long have they managed the fund?\n4. AUM (Assets Under Management): Very large or very small AUM can be a concern\n5. Consistency: A fund that gives 12% consistently beats one that alternates between 25% and -5%\n\nStart simple: A Nifty 50 index fund is the best first investment for most beginners.",
                keyTakeaway: "For beginners: Start with a Nifty 50 index fund. Low cost, diversified, and historically strong returns.",
                icon: "Search",
            },
        ],
        quiz: [
            {
                id: "mfq1",
                type: "mcq",
                question: "What does NAV stand for?",
                options: [
                    "Net Annual Value",
                    "Net Asset Value",
                    "New Asset Valuation",
                    "National Average Value",
                ],
                correctIndex: 1,
                explanation: "NAV (Net Asset Value) is the per-unit market value of all the securities held by the fund, minus liabilities.",
                xpReward: 20,
            },
            {
                id: "mfq2",
                type: "mcq",
                question: "What is the main advantage of SIP (Systematic Investment Plan)?",
                options: [
                    "Guaranteed returns",
                    "Tax-free investments",
                    "Rupee cost averaging and discipline",
                    "Higher interest rate than FD",
                ],
                correctIndex: 2,
                explanation: "SIP averages out market volatility (rupee cost averaging) and builds investing discipline through automatic monthly investments.",
                xpReward: 20,
            },
            {
                id: "mfq3",
                type: "true-false",
                question: "Index funds typically have lower expense ratios than actively managed funds.",
                correctAnswer: true,
                explanation: "Index funds simply track a market index (like Nifty 50) and don't need active management, resulting in expense ratios of 0.1-0.5% vs 0.5-2.5% for active funds.",
                xpReward: 20,
            },
            {
                id: "mfq4",
                type: "scenario",
                question: "Meera is 25, just started her career, wants to invest for retirement. What's the best approach?",
                scenario: "Meera earns ₹6 LPA and can save ₹5,000/month. She has 35 years until retirement and can tolerate short-term market volatility.",
                options: [
                    { label: "100% in fixed deposits", description: "Safe and guaranteed returns" },
                    { label: "75% equity funds, 25% debt funds via SIP", description: "Aggressive but age-appropriate" },
                    { label: "100% in gold", description: "Gold is always valuable" },
                    { label: "50% savings account, 50% real estate", description: "Balanced and tangible" },
                ],
                correctIndex: 1,
                explanation: "At 25, Meera has time on her side. The rule of thumb (100 - age = equity %) suggests ~75% in equity. SIP ensures discipline and rupee cost averaging.",
                xpReward: 25,
            },
            {
                id: "mfq5",
                type: "slider",
                question: "Using the '100 minus age' rule, what % of a 35-year-old's portfolio should be in equity?",
                min: 0,
                max: 100,
                step: 5,
                unit: "%",
                correctValue: 65,
                tolerance: 10,
                explanation: "100 - 35 = 65%. At 35, approximately 65% in equity and 35% in debt provides a good balance of growth and stability.",
                xpReward: 25,
            },
            {
                id: "mfq6",
                type: "mcq",
                question: "Which type of mutual fund is best for parking money for 1-3 months?",
                options: [
                    "Small cap equity fund",
                    "Liquid fund",
                    "ELSS tax-saving fund",
                    "Balanced hybrid fund",
                ],
                correctIndex: 1,
                explanation: "Liquid funds invest in very short-term debt instruments, offering slightly better returns than savings accounts with high liquidity. Perfect for short-term parking.",
                xpReward: 20,
            },
            {
                id: "mfq7",
                type: "true-false",
                question: "You need at least ₹10,000 to start investing in mutual funds.",
                correctAnswer: false,
                explanation: "Many mutual funds allow SIPs starting at just ₹100-500 per month. The barrier to entry is extremely low.",
                xpReward: 20,
            },
            {
                id: "mfq8",
                type: "mcq",
                question: "What does a lower expense ratio mean for an investor?",
                options: [
                    "The fund is riskier",
                    "More of your returns stay with you",
                    "The fund has fewer stocks",
                    "The fund manager is less experienced",
                ],
                correctIndex: 1,
                explanation: "Expense ratio is the annual fee charged by the fund. A lower expense ratio means less of your returns go to fees and more stays in your pocket.",
                xpReward: 20,
            },
        ],
    },

    // ================================================================
    // MODULE 5: CREDIT SCORES
    // ================================================================
    {
        slug: "credit-scores",
        title: "Credit Scores",
        subtitle: "Reputation RPG",
        description: "Your financial reputation in one number. Learn what affects it and how to build it.",
        icon: "Star",
        color: "#e17055",
        gradientFrom: "#e17055",
        gradientTo: "#fab1a0",
        difficulty: "intermediate",
        estimatedMinutes: 15,
        lessons: [
            {
                id: "cs1",
                title: "What is a Credit Score?",
                content: "A credit score is a 3-digit number (300-900 in India, via CIBIL) that represents your creditworthiness — how likely you are to repay borrowed money.\n\nWhy it matters:\n• Loan approval: Banks check this FIRST\n• Interest rates: Higher score = lower rates (saves lakhs)\n• Rental applications: Landlords may check it\n• Job applications: Some employers check it\n• Credit card approvals: Determines your limit\n\nScore ranges:\n• 750-900: Excellent — best rates, instant approvals\n• 700-749: Good — most loans approved easily\n• 650-699: Fair — approved with conditions\n• Below 650: Poor — limited options, higher rates",
                keyTakeaway: "Your credit score is your financial reputation score. A good score (750+) literally saves you money through lower interest rates.",
                icon: "Star",
            },
            {
                id: "cs2",
                title: "The 5 Factors That Build Your Score",
                content: "Your credit score is calculated from 5 factors:\n\n1. Payment History (35%): Do you pay on time? Even one missed payment hurts significantly.\n\n2. Credit Utilization (30%): How much of your available credit are you using? Keep it below 30%.\n   • ₹1 lakh credit limit → use less than ₹30,000\n\n3. Credit Age (15%): How long have you had credit accounts? Longer = better.\n\n4. Credit Mix (10%): Having different types of credit (credit card, loan, etc.) shows you can manage various debts.\n\n5. New Credit (10%): Too many credit applications in a short period looks desperate.",
                keyTakeaway: "Payment history + credit utilization = 65% of your score. Pay on time and keep utilization under 30%.",
                icon: "BarChart",
                interactiveExample: {
                    type: "calculator",
                    label: "Try the Credit Score Simulator",
                    description: "Head to the Playground to simulate score changes",
                },
            },
            {
                id: "cs3",
                title: "Building Credit From Scratch",
                content: "No credit history? Here's the roadmap:\n\n1. Start with a secured credit card: Deposit ₹25,000, get ₹25,000 credit limit. Zero risk for the bank.\n\n2. Use it responsibly: Small purchases (5-10% of limit), pay FULL balance every month.\n\n3. Never miss a payment: Set up auto-pay for the minimum, then manually pay the full amount.\n\n4. Graduate to a regular card: After 6-12 months of perfect history, apply for an unsecured card.\n\n5. Don't close old cards: Your first card is the foundation of your credit age. Keep it active with a small recurring charge.\n\nTimeline: 6-12 months to establish a score, 2-3 years to build a good score (700+).",
                keyTakeaway: "Building credit is a marathon, not a sprint. Start with a secured card and be religiously consistent with payments.",
                icon: "TrendingUp",
            },
            {
                id: "cs4",
                title: "Credit Card Traps to Avoid",
                content: "Credit cards are powerful tools that become dangerous weapons if misused:\n\n🚫 Minimum Payment Trap: Paying only the minimum (5% of balance) means the rest accrues interest at 36-42% per year. A ₹50,000 balance can take 10+ years to pay off.\n\n🚫 Cash Advances: Withdrawing cash from credit cards charges 2.5-3.5% per month PLUS a flat fee. Never do this.\n\n🚫 Multiple Applications: Each application is a 'hard inquiry' that drops your score 5-10 points.\n\n🚫 Maxing Out: Using 100% of your limit tanks your utilization ratio.\n\n✅ Golden Rule: Treat your credit card like a debit card. If you can't pay the full balance this month, you can't afford it.",
                keyTakeaway: "Credit cards are free money ONLY if you pay the full balance every month. Otherwise, they're the most expensive loan you can take.",
                icon: "AlertTriangle",
            },
        ],
        quiz: [
            {
                id: "csq1",
                type: "mcq",
                question: "What is the most important factor in your credit score?",
                options: [
                    "Credit utilization (30%)",
                    "Payment history (35%)",
                    "Credit age (15%)",
                    "Credit mix (10%)",
                ],
                correctIndex: 1,
                explanation: "Payment history accounts for 35% of your score — the single largest factor. Never miss a payment, even the minimum.",
                xpReward: 20,
            },
            {
                id: "csq2",
                type: "slider",
                question: "What's the recommended maximum credit utilization ratio?",
                min: 0,
                max: 100,
                step: 5,
                unit: "%",
                correctValue: 30,
                tolerance: 15,
                explanation: "Keep credit utilization below 30% of your total credit limit. If you have a ₹1 lakh limit, use less than ₹30,000.",
                xpReward: 25,
            },
            {
                id: "csq3",
                type: "true-false",
                question: "Closing your oldest credit card can reduce your credit score.",
                correctAnswer: true,
                explanation: "Closing your oldest card reduces your average credit age (15% of score) and reduces total available credit (increasing utilization ratio). It's better to keep old cards active.",
                xpReward: 20,
            },
            {
                id: "csq4",
                type: "scenario",
                question: "Neha has a credit card with ₹2 lakh limit. She spent ₹1.5 lakh this month and can only pay ₹20,000 now. What should she do?",
                scenario: "Neha's statement shows ₹1,50,000 balance. Minimum payment is ₹7,500. She has ₹20,000 available right now and gets paid in 10 days.",
                options: [
                    { label: "Pay minimum ₹7,500, deal with rest later", description: "Avoid late fee, worry later" },
                    { label: "Pay ₹20,000 now, pay rest immediately when paid", description: "Reduce balance ASAP and clear before interest" },
                    { label: "Skip this month's payment", description: "Pay double next month instead" },
                    { label: "Take a cash advance to pay the balance", description: "Use another card to pay this one" },
                ],
                correctIndex: 1,
                explanation: "Pay as much as possible now (₹20,000) and clear the remaining balance as soon as you get paid — before the interest-free period ends. Never skip payments or use cash advances.",
                xpReward: 25,
            },
            {
                id: "csq5",
                type: "mcq",
                question: "What happens when you only pay the minimum balance on your credit card?",
                options: [
                    "Nothing — it's a normal way to use credit cards",
                    "The remaining balance accrues interest at 36-42% annually",
                    "The bank forgives the rest of the balance",
                    "Your credit limit increases automatically",
                ],
                correctIndex: 1,
                explanation: "Paying only the minimum means the rest of your balance gets charged interest at 36-42% per year — one of the highest interest rates on any financial product.",
                xpReward: 20,
            },
            {
                id: "csq6",
                type: "mcq",
                question: "How can someone with no credit history start building credit?",
                options: [
                    "Apply for multiple credit cards at once",
                    "Take a large personal loan",
                    "Get a secured credit card and use it responsibly",
                    "Add themselves as a guarantor on someone's loan",
                ],
                correctIndex: 2,
                explanation: "A secured credit card (backed by a deposit) is the safest way to start. Use it for small purchases and pay in full every month to build a positive payment history.",
                xpReward: 20,
            },
            {
                id: "csq7",
                type: "true-false",
                question: "Checking your own credit score lowers it.",
                correctAnswer: false,
                explanation: "Checking your own score is a 'soft inquiry' and does NOT affect your score. Only 'hard inquiries' (when lenders check for loan/card applications) impact it.",
                xpReward: 20,
            },
            {
                id: "csq8",
                type: "slider",
                question: "A credit score of 750+ in India is generally considered:",
                min: 0,
                max: 4,
                step: 1,
                unit: "rating",
                correctValue: 0,
                tolerance: 0,
                explanation: "A CIBIL score of 750+ is considered 'Excellent' and qualifies you for the best interest rates and instant loan approvals.",
                xpReward: 20,
            },
        ],
    },
];

// Helper: Get module by slug
export function getModuleBySlug(slug: string): GameModule | undefined {
    return GAME_MODULES.find((m) => m.slug === slug);
}